name: shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  provider: ^6.1.5

  # Firebase (νΈν™ λ²„μ „)
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.1.0
  firebase_ui_auth: ^1.13.1
  firebase_storage: ^12.4.10
  image_picker: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/my_splash_logo.png"

flutter_native_splash:
  android: true
  ios: true

  color: "#73FF77"
  image: assets/splash.png

  fullscreen: true
  android_gravity: center

  android_12:
    image: assets/splash.png
    color: "#73FF77"
    icon_background_color: "#73FF77"


flutter:
  uses-material-design: true

  assets:
    - assets/my_splash_logo.png
